### ISSUE TITLE
Update to your lutris install script

### ISSUE THREAD

**Issue by OJ2024** [Streamerbot/sb-linux-installer#10]
Cleanup of the lutris install script for you:

```
name: Streamer.bot
description: Supercharge your live stream with Streamer.bot
game_slug: streamerbot
year: 2021
version: Streamer.bot (Latest)
slug: streamerbot-latest
runner: wine

script:
    files:
    - streamerbot:
        filename: streamerbot.zip
        url: https://streamer.bot/api/releases/streamer.bot/latest/download
    game:
     exe: $GAMEDIR/drive_c/App/Streamer.bot.exe
     prefix: $GAMEDIR
     working_dir: $GAMEDIR

   installer: 
    - task:
        name: create_prefix
        description: Creating Wine prefix
        arch: win64
        prefix: $GAMEDIR
        install_mono: false
        install_gecko: true
    - task:
        name: winetricks
        description: Installing .NET 4.8 will take a while...
        app: dotnet48
        prefix: $GAMEDIR
    - task:
        name: winetricks
        description: Installing d3dcompiler_47...
        app: d3dcompiler_47
        prefix: $GAMEDIR
    - task:
        name: winetricks
        description: Installing corefonts...
        app: corefonts
        prefix: $GAMEDIR
    - extract:
        file: streamerbot
        dst: $GAMEDIR/drive_c/App
   wine:
       version: lutris-7.2-2-x86_64
```
Installs and launches with wine-ge-8-26 on lutris 0.5.16 - it does not actually run - there is a bug in the release version of lutris that prevents me from setting the correct wine version for it to install and run in the script. This has been fixed in the git pull (master) of lutris, and AUR on Arch linux. Other distros with lutris 0.5.16 will need to install the lutris-7.2-2 wine from the left hand pane in lutris -> runners -> wine -> click the folder icon and install this wine version. They will then need to right click streamer.bot in lutris -> configure -> runner options tab and select lthe wine version: lutris-7.2-2 from the drop down and save.
